/*
 * redis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redisenterprise

type Database struct {
	Uid int32 `json:"uid,omitempty"`
	Status DatabaseStatus `json:"status,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
	Port int32 `json:"port,omitempty"`
	MemorySize int64 `json:"memory_size,omitempty"`
	Sharding bool `json:"sharding,omitempty"`
	ShardsCount int32 `json:"shards_count,omitempty"`
	ShardsPlacement string `json:"shards_placement,omitempty"`
	ShardKeyRegex []DatabaseShardKeyRegexItem `json:"shard_key_regex,omitempty"`
	ImplicitShardKey bool `json:"implicit_shard_key,omitempty"`
	Replication bool `json:"replication,omitempty"`
}
