/*
 * redis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redisenterprise
type DatabaseStatus string

// List of DatabaseStatus
const (
	PENDING DatabaseStatus = "pending"
	ACTIVE DatabaseStatus = "active"
	ACTIVE_CHANGE_PENDING DatabaseStatus = "active-change-pending"
	DELETE_PENDING DatabaseStatus = "delete-pending"
	IMPORT_PENDING DatabaseStatus = "import-pending"
	CREATION_FAILED DatabaseStatus = "creation-failed"
	RECOVERY DatabaseStatus = "recovery"
)