/*
 * redis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redisenterprise

type Error struct {
	ErrorCode string `json:"error_code,omitempty"`
	Description string `json:"description,omitempty"`
}
